# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julien Dufresne
email: blog@dfrsn.me
description: >
  Julien Dufresne &cir; Senior Software Developer &amp; Solution Architect
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.juliendufresne.fr" # the base hostname & protocol for your site

exclude:
  - docker.md
  - github-example.md
  - watch.sh

# Build settings
markdown: kramdown
